# Generated by Django 4.2.7 on 2023-12-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(max_length=11)),
            ],
        ),
    ]
