# Generated by Django 4.2.7 on 2023-12-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
